### ISSUE TITLE
[Question] # REINSTALL ELIGIBLE BINARIES

### ISSUE THREAD

**Issue by JayDee696969** [drinfernoo/plugin.program.aftermath#130]
Is this feature active? Can you explain a little? It seems if I have a build_binaries.txt file somewhere it will install specified binaries on first install?? This could be usefull, so Im just curious how/if this is implemented or not.
In startup.py:

# REINSTALL ELIGIBLE BINARIES
binarytxt = os.path.join(CONFIG.USERDATA, 'build_binaries.txt')
if os.path.exists(binarytxt):
    logging.log("[Binary Detection] Reinstalling Eligible Binary Addons", level=xbmc.LOGINFO)
    from resources.libs import restore
    restore.restore('binaries')
else:
    logging.log("[Binary Detection] Eligible Binary Addons to Reinstall", level=xbmc.LOGINFO)

**Comment by SerpentDrago** [comment]
yeh just make your build backup  WITH the wizard and thats all you have to do , the wizard handles everything. then  when a user then installs that build it will auto reinstall the platform specific binaries  and fix the kodi db

**Comment by drinfernoo** [comment]
Always make your builds using the wizard, and then this will work for you, yes. It **is** useful, implemented, and functional.

**Comment by JayDee696969** [comment]
> yeh just make your build backup WITH the wizard and thats all you have to do , the wizard handles everything. then when a user then installs that build it will auto reinstall the platform specific binaries and fix the kodi db

Hmm, interesting. So let me get this straight. The build must be backed up from the wizard for this to work correct? So any platform specific binaries will be overwritten and the correct platform binaries will be reinstalled on first install?? And this also takes care of the addon33.db at the same time correct? Very nice. I guess I never tried it because I always zip up my build on my PC from the Kodi folder. Very cool. Before I was making dummy/empty  binary addons folders in the addons folder with a lower version # so kodi would update them with the correct platform binary on first install. And I was also editing the addons.33 db file manually before zipping. Well, this sounds much easier, lol.

**Comment by SerpentDrago** [comment]
yeh to be clear it doesn't "overwrite" them.  the wizard when making the backup simply removes them, Cleans them from the db  , sets the version of all repos installed to like .1 and zips it . Then when you restore / install that build , kodi will see there is "updates" to the repos making it reinstall them and thous fixing the db entries of what they contain .  so you will get the correct platform specific binarys , when the wizard then auto  reinstalls them after the first reboot. its a fucking killer feature and i spent a shit load of time testing all this for Dr .

**Comment by JayDee696969** [comment]
> yeh to be clear it doesn't "overwrite" them. the wizard when making the backup simply removes them, Cleans them from the db , sets the version of all repos installed to like .1 and zips it . Then when you restore / install that build , kodi will see there is "updates" to the repos making it reinstall them and thous fixing the db entries of what they contain . so you will get the correct platform specific binarys , when the wizard then auto reinstalls them after the first reboot. its a fucking killer feature and i spent a shit load of time testing all this for Dr .

And I can totally appreciate your efforts, I understand what that entails bro. Nice job!

**Comment by JayDee696969** [comment]
By the way, ive edited the debridit and traktit files to include all the latest Matrix addons along with the saved data entries in settings. If you guys want to use it in the wizard let me know.

**Comment by SerpentDrago** [comment]
make a PR  ! 

Just fork this project , make your changes to the correct branch "matrix" then make a PR to this repo and branch

**Comment by JayDee696969** [comment]
Ill give it a go. Make want to look it over, but everything seems to save correctly so far.
