### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by pauly001** [drinfernoo/plugin.program.aftermath#136]
Does the wizard support the “Addon Installer” feature? I do not see an addons.txt template. I see builds.txt, apk.txt, etc. if so, is there a template so the wizard can install my Kodi addons directly? I don’t have a repository for my addons. If not, no worries. Thanks for the hard work for those of us who rely on this wizard. I love it.

**Comment by drinfernoo** [comment]
https://github.com/a4k-openproject/plugin.program.openwizard/wiki/Installing-Add-ons
