### ISSUE TITLE
Request to add playercorefactory.xml to exempt list

### ISSUE THREAD

**Issue by bsweet0us** [drinfernoo/plugin.program.aftermath#3]
There is a user-created xml file called "playercorefactory.xml" that controls how KODI handles external players.  It resides in the C:\Users\USERNAME\AppData\Roaming\Kodi\userdata folder on Windows machines (not sure where it's housed on other iterations) and currently gets deleted when updating.

I think it can be added to the "whitelist" on the back end, but I can't through the edit whitelist option within the "build."

I'll try to provide more info as needed, just let me know and thanks for looking into this!

**Comment by drinfernoo** [comment]
I believe this should be implemented as of b60504175355a3eb786af2366b824f8baeac1b2d, so I'm going to close this for now. If you'd like to test and let me know, that'd be great.
