### ISSUE TITLE
inputstream.adaptive needs to be excluded from build wizard

### ISSUE THREAD

**Issue by SerpentDrago** [drinfernoo/plugin.program.aftermath#39]
Because of the binary nature of the DRM , its platform dependent and should be excluded from auto build zip creation or restoring .

**Comment by drinfernoo** [comment]
And we think the fix to this is to make the build zip exclude just the `addons/inputstream.adaptive` folder, or also the addon_data/inputstream.adaptive` folder?

What about `script.module.inputstreamhelper`?

**Comment by drinfernoo** [comment]
To be closed in a coming commit.
