### ISSUE TITLE
error after updating[BUG]

### ISSUE THREAD

**Issue by Payasiando** [drinfernoo/plugin.program.aftermath#4]
**Describe the bug**
doing a wizard update and changing the version of the wizard to get auto-updates advising there is an update, all goes well, update install no problem, but a couple seconds after it gives an error message. I check that the update went through, a new version number is there, the artwork is there, all changes made are there. yes, all is good. whats throwing me off is that error that pops up after. tried a couple of changes in the uservar (disabling notifications) as adviced. starting with a fresh aftermath folder as a base just transferring my addon.xml and uservar files to the new base. again all goes well as for as the update goes just that error message at the end of the update. attached are the wizard.log and kodi.log. 
[kodi.log](https://github.com/drinfernoo/plugin.program.aftermath/files/2892503/kodi.log)
[wizard.log](https://github.com/drinfernoo/plugin.program.aftermath/files/2892504/wizard.log)

**Platform**
Windows 10  Operating system and 
version 18.0 of Kodi the bug is occurring on.

**Additional context**
tried various times with advice from others and still same issue.

**Comment by drinfernoo** [comment]
@Payasiando Is this bug still present? I can no longer see your logs.

**Comment by drinfernoo** [comment]
Confirmed to no longer be an issue by @Payasiando 👍
