### ISSUE TITLE
[FEATURE]4K wallpaper ability within Kodi - Enhance 

### ISSUE THREAD

**Issue by kodiultimate** [drinfernoo/plugin.program.aftermath#5]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
OK, will start with little explanation. Today if anyone would like to use 4K wallpapers within their 'build' will end up with max resolution which is 1080p. By default kodi is set to cache thumbnails at maximum resolution of 1080p.
So technically at the moment no point doing so because we will end up with 1080p res anyway.
Here is solution as per instruction by Team-Kodi member:
To get maximum resolution wallpaper we need to add an extra line to the advancedsettings.xml file.
Which is: <imageres>9999</imageres>
With this extra line Kodi will set thumbnails cache to the max resolution.
Now question is, if this option could be added to the Quick Advanced Settings? as an extra option to pick and the file will be generated with that extra line?

Is just my wondering and could be possibly extra feature? 
Thanks drinfernoo

**Comment by drinfernoo** [comment]
Closing, as this can potentially be an included setting once #30 is implemented.
