### ISSUE TITLE
Tools Section

### ISSUE THREAD

**Issue by TheGridRepo** [drinfernoo/plugin.program.aftermath#52]
any way of fixing the delete selected addon.... doesn't seam to be working...or might just be me...

**What accounts does this add-on support?**
Does this add-on have compatibility with Trakt, any debrid services, or any other API keys or accounts? Which ones?

**Where is this add-on available?**
This could be a GitHub repo, a Kodi repo, or even just a file manager source.

**Comment by drinfernoo** [comment]
Can you provide a log file when you choose the option? I didn't know it was broken.

**Comment by drinfernoo** [comment]
@TheGridRepo Can you provide anymore information?

**Comment by drinfernoo** [comment]
I'm closing this issue unless more information is supplied. I cannot replicate the issue... because I don't know what it is.
