### ISSUE TITLE
Adding sections from wizard to favorites.

### ISSUE THREAD

**Issue by JayDigg** [drinfernoo/plugin.program.aftermath#54]
Ok, so this issue only applies to Kodi 18. 17 works fine.
I prefer to add sections from the wizard to favorites to make home screen shortcuts to various sections in the wizard. For example Speedtest, Total CleanUp, Advanced settings, View error logs, etc. 
How to replicate issue: Open the wizard maintenance sections. Add any of the listed sections as shown above to Kodi favorites. Try to open the favorite that was made to the section.
Behavior: The section opens correctly, however you can not close it when done, just constantly reopens over and over again. 
Fix, so for example the fix that makes Total Clean shortcut to work properly is to add the line sys.exit(0) to the end at def totalClean() Line 2338 in default.py. 
def totalClean():
    if DIALOG.yesno(ADDONTITLE, '[COLOR %s]Would you like to clear cache, packages and thumbnails?[/COLOR]' % COLOR2, nolabel='[B][COLOR red]Cancel Process[/COLOR][/B]',yeslabel='[B][COLOR springgreen]Clean All[/COLOR][/B]'):
        wiz.clearCache()
        wiz.clearPackages('total')
        clearThumb('total')
	sys.exit(0)

Maybe you know a better way to do this so it works the same for other sections also?

**Comment by drinfernoo** [comment]
The only issue I see with your "solution" is that it would make the wizard exit even if the shortcut is chosen from *inside* the wizard.

**Comment by drinfernoo** [comment]
Have you tried this solution? Is it working on your end?

**Comment by JayDigg** [comment]
Yes, for this example I added the sys.exit(0) under def totalClean, and that made it work when I added the Total Cleanup shortcut as a favorite and ran the favorite. If the code isnt there it will loop and keep prompting to autoclean. Give it a try and see. I just am not sure where else to add it to fix the other sections.

**Comment by drinfernoo** [comment]
Will you open a PR for this so I can test it more thoroughly?

**Comment by JayDigg** [comment]
![screenshot_1](https://user-images.githubusercontent.com/45118866/52296377-341bc800-294c-11e9-81e7-615e3085ebe8.png)

**Comment by JayDigg** [comment]
Sorry, not to versed on using Github, but its just that one line in default.py

**Comment by JayDigg** [comment]
Not sure if its the best method either, and not sure how to implement it for the rest, but it does work for this example at least.

**Comment by JayDigg** [comment]
`<favourites>
    <favourite name="[COLOR dodgerblue]Total Clean Up: [COLOR springgreen][B]2.00 MB[/B][/COLOR][/COLOR]" thumb="C:\Users\Modline\AppData\Roaming\Kodi\addons\plugin.program.aftermath\resources\art\maintenance.png">PlayMedia(&quot;plugin://plugin.program.aftermath/?mode=fullclean&quot;)</favourite>
    <favourite name="[COLOR dodgerblue][B][I]([COLOR white]Aftermath[/COLOR])[/I][/B][/COLOR] [COLOR white]Speed Tester[/COLOR]" thumb="C:\Users\Modline\AppData\Roaming\Kodi\addons\plugin.program.aftermath\resources\art\apkinstaller.png">ActivateWindow(10001,&quot;plugin://plugin.program.aftermath/?mode=speedtestM&quot;,return)</favourite>
    <favourite name="[COLOR dodgerblue]Quick Configure AdvancedSettings.xml[/COLOR]" thumb="C:\Users\Modline\AppData\Roaming\Kodi\addons\plugin.program.aftermath\resources\art\maintenance.png">PlayMedia(&quot;plugin://plugin.program.aftermath/?mode=autoadvanced&quot;)</favourite>
</favourites>`

**Comment by JayDigg** [comment]
You can see for yourself by just adding a section to favorites and try opening it from favorites.

**Comment by JayDigg** [comment]
![screenshot_2](https://user-images.githubusercontent.com/45118866/52301984-d9896880-2959-11e9-9a6a-dd79d68f19c4.png)

**Comment by kodiultimate** [comment]
Guys,
Sorry to jumping into this as I was looking for the solution to the above issue. Thought it maybe Super Favourites + Kodi 18 issue but this thread showing me that there is general within Kodi 18.
Just to add. Exactly same behaviour we will end up with while using Super Favourites. Here is more details:
Create Folder (any name) within Super Favourites addon + add one of the Wizard section to it. Then try to open that folder within Super Favourites addon  and use just added section. You will end up with the same behaviour. Loop which will go away after 7 or 8 times.

**Comment by FireTvGuru** [comment]
the main issue is the wiz.refresh() after most of the modes is looping and kodi stops it but after about 60 secs.

To solve: Add sys.exit(0) as shown

![2019-02-05 22_03_58-c__kodi_kodi18-rel_portable_data_addons_plugin program thechef_default py - note](https://user-images.githubusercontent.com/36491670/52319960-035e8180-2992-11e9-939f-4187fbb11ee2.jpg)

![2019-02-05 22_02_21-c__kodi_kodi18-rel_portable_data_addons_plugin program thechef_resources_libs_wi](https://user-images.githubusercontent.com/36491670/52319920-c5f9f400-2991-11e9-9e84-ba4d81a95284.jpg)

**Comment by SerpentDrago** [comment]
Dr , i confirm i have this issue also , I thought it was just me !~ lol , and i didn't do this action enough to warrant looking into it , as i could just get out by hitting back enough !

**Comment by drinfernoo** [comment]
I tested my latest @FireTvGuru's fixes against Total Cleanup, and it seems to work for me. Can you confirm @SerpentDrago or @JayDigg?

**Comment by kodiultimate** [comment]
Its working fine on my side, however when I downloaded master version 0.4.6 from your git sys.exit(0) is missing??

def viewSpeedTest(img=None):
    img = os.path.join(SPEEDTESTFOLD, img)
    notify.speedTest(img)

**Comment by drinfernoo** [comment]
@kodiultimate Try the develop branch.

**Comment by kodiultimate** [comment]
Done it now.
There is some more areas where "sys.exit(0)" needs to be added, for example wizard.py
Most of them I have located myself and fixed but I do have issue with "uploadlog" option.
Basically when Upload Option is added to favourites, and then used from there, it's looping the upload window and keeps re-sending log file to the pastebin. So we end up with 6 or 7 log files on the pastebin server.
Could you please have a look at this?

**Comment by drinfernoo** [comment]
@kodiultimate If you'd get me a list of places that are still doing it for you, I'd love to fix them 👍

**Comment by kodiultimate** [comment]
Ideally will need a help just with uploadLog.py as it seems to be tricky :)

I will try to contribute with other stuff and if you are happy you can merge ;) thanks

**Comment by drinfernoo** [comment]
@kodiultimate What happens when you have Uploaded Log in a Kodi favorite? Can you send a small video, maybe?

**Comment by kodiultimate** [comment]
Here it is. Sorry I had to use Mega

https://mega.nz/#!eIYGVS7L!bqyoVIrAZ_V2p2oTRewZ6cWiFABzeoXSBltAloQeRcA

**Comment by drinfernoo** [comment]
@kodiultimate I believe I've fixed uploadLog, but if you have any more areas you want me to look at, feel free.

**Comment by kodiultimate** [comment]
Thanks @drinfernoo  appreciate it! One more:

Could you have a look at Force Update (addons) function please? I have tried within wizard.py 
  " def forceUpdate(silent=False): "  but I had no luck adding  sys.exit(0) at the end.

Thanks
