### ISSUE TITLE
System Information Broken

### ISSUE THREAD

**Issue by FireTvGuru** [drinfernoo/plugin.program.aftermath#55]
The mode:
'systeminfo'     : systemInfo()
is broken due to the old url for the ip address info and its duplicated 

![2019-02-05 21_21_56-_c__kodi_kodi18-rel_portable_data_addons_plugin program thechef_default py - not](https://user-images.githubusercontent.com/36491670/52318871-300f9a80-298c-11e9-856b-8c478c598697.jpg)

the Fix:

    addFile('[B]Network:[/B]', '', icon=ICONMAINT, themeit=THEME2)
    mac,inter_ip,ip,city,state,country,isp = wiz.net_info()
    addFile('[COLOR %s]Mac:[/COLOR] [COLOR %s]%s[/COLOR]' % (COLOR1, COLOR2, mac), '', icon=ICONMAINT, themeit=THEME2)
    addFile('[COLOR %s]Internal IP: [COLOR %s]%s[/COLOR]' % (COLOR1, COLOR2, inter_ip), '', icon=ICONMAINT, themeit=THEME2)
    addFile('[COLOR %s]External IP:[/COLOR] [COLOR %s]%s[/COLOR]' % (COLOR1, COLOR2, ip), '', icon=ICONMAINT, themeit=THEME2)
    addFile('[COLOR %s]City:[/COLOR] [COLOR %s]%s[/COLOR]' % (COLOR1, COLOR2, city), '', icon=ICONMAINT, themeit=THEME2)
    addFile('[COLOR %s]State:[/COLOR] [COLOR %s]%s[/COLOR]' % (COLOR1, COLOR2, state), '', icon=ICONMAINT, themeit=THEME2)
    addFile('[COLOR %s]Country:[/COLOR] [COLOR %s]%s[/COLOR]' % (COLOR1, COLOR2, country), '', icon=ICONMAINT, themeit=THEME2)
    addFile('[COLOR %s]ISP:[/COLOR] [COLOR %s]%s[/COLOR]' % (COLOR1, COLOR2, isp), '', icon=ICONMAINT, themeit=THEME2)

**Comment by kodiultimate** [comment]
Still can't get this work correctly, am I missing something?

Thanks

**Comment by drinfernoo** [comment]
Thanks, I've fixed it :thumbsup:
