### ISSUE TITLE
Quick cosmetic fix. Noticed the speed test icon wasn't showing up in the addon even though I linked it in uservar

### ISSUE THREAD

**Issue by bigpoppapaul** [drinfernoo/plugin.program.aftermath#56]
default.py was missing 
ICONSPEED        = uservar.ICONSPEED if not uservar.ICONSPEED == 'http://' else ICON
I added it to line 162 so it's in the same order as the icon links in uservar

820, 913, 918, 919 - changed iconmaint to iconspeed
896 - changed iconapk to iconspeed

**Comment by drinfernoo** [comment]
On line 896, it probably should still be `iconapk`, as that's for the APK Installer section, rather than the Speed Test section. I'd be open to a PR if you wanted?

**Comment by bigpoppapaul** [comment]
Really? For me, line 896 is: addDir ('Speed Tester' ,'speedtestM', icon=ICONAPK, themeit=THEME1)
Which creates this icon here: 
![iconapk](https://user-images.githubusercontent.com/20094991/52387888-f3aa7000-2a59-11e9-8ee2-eb9adae00d00.JPG)
However, if I change it to iconspeed, I get this, it doesn't seem to affect the images in apk installer at all: 
![iconspeed](https://user-images.githubusercontent.com/20094991/52387997-5e5bab80-2a5a-11e9-900f-444fa34d67c4.JPG)

**Comment by drinfernoo** [comment]
Ah, maybe you're right. I'll probably merge an applicant PR 👍

**Comment by drinfernoo** [comment]
Are you going to open a PR, or should I make the changes myself?

**Comment by bigpoppapaul** [comment]
I'm very new to t

**Comment by drinfernoo** [comment]
@bigpoppapaul What you'll want to do is fork this repository, make a new branch, make your changes, then open a pull request from that branch to my `develop` branch. [This seems like a pretty good guide](https://kbroman.org/github_tutorial/pages/fork.html) that I just found on Google 👍

**Comment by bigpoppapaul** [comment]
Alright, thanks for the tips, I'll look at that guide and make my way through it. :)

**Comment by bigpoppapaul** [comment]
Done.
