### ISSUE TITLE
[BUG] IARL/IAGL Cache Cleaning

### ISSUE THREAD

**Issue by JayDigg** [drinfernoo/plugin.program.aftermath#57]
Clearing IAGL cache 

I noticed the IAGL cache added to the wizard cleaning tools. I hope the function doesnt delete temp_IAGL and temp_list_cache folders. 
If so, this will delete all downloaded games and last played history. I dont know why anybody would want that to happen. Then you would have to redownload all the games everytime you play and will delete all game history. IAGL already has an option is settings to choose how much cached games you prefer to store. If this is the case i dont think this should be included, or at least have an option to not enable this cache clearing. Thanks!

**Comment by drinfernoo** [comment]
You know what? You're totally right and I've been meaning to fix it. Thanks for reminding me :)

**Comment by JayDigg** [comment]
Awesome, thanks!

**Comment by drinfernoo** [comment]
I'll probably simply leave out the clearing of `temp_list_cache` (or maybe just the player history?), but how about making `temp_iagl` part of the video cache clearing options?

**Comment by JayDigg** [comment]
Well, no. I would suggest neither. The temp_iagl is where the roms are downloaded to by default. Clearing this would wipe your downloaded games.  And list_cache is where your played game history is stored along with the game lists. Plus clearing the list_cache is pretty pointless because it just has to redownload the list when you open the system list again. I prefer and suggest to leave it alone, dont clear any of that. IMO.

**Comment by JayDigg** [comment]
Also, I believe customization to each game list as for default emulator options along with your hidden IARL lists are also stored in list_cache. Deleting that would also delete all your custom launch commands and preferences set for each list, which would be very frustrating, lol.

**Comment by JayDigg** [comment]
These context menu customizations for each list  are stored in these list_cache and would not be good to clear.
![screenshot_1](https://user-images.githubusercontent.com/45118866/52501691-efdc3200-2bae-11e9-834f-b08093334eac.png)

**Comment by drinfernoo** [comment]
I'll make some fixes soon.
