### ISSUE TITLE
[BUG] Wizard auto-generate advancedsettings.xml? Bug of feature ?

### ISSUE THREAD

**Issue by kodiultimate** [drinfernoo/plugin.program.aftermath#58]
**Describe the bug**

First of all, thank you so much for keeping this wizard alive! great job.
OK to the point, I'm not really sure whenever this is a bug or feature?
Clean install of Kodi 18 and Aftermath wizard seems to be auto-generating advancedsettings.xml file with the value of:

  _advancedsettings
	network
		buffermode2/buffermode
		cachemembuffersize**209715200**/cachemembuffersize
		readbufferfactor5/readbufferfactor
		curlclienttimeout10/curlclienttimeout
		curllowspeedtime10/curllowspeedtime
	/network
/advancedsettings_

After running Quick Configure AdvanceSettings.xml option trough wizard it detects that there is a previous advancedsettings.xml file and asking for overwriting it. After doing so the value for my device has changed to:

 _cachemembuffersize**411041792**/cachemembuffersize_

So its seems like auto-generate value wasn't correct for my device. Question is can this be disabled and let the user generate correct advancedsettings.xml by doing so within wizard?

Thanks drinfernoo

**Platform**
Android v 9 on mobile

**Comment by drinfernoo** [comment]
Technically, it's a feature, but I'm open to suggestions on how it would better. I'm not fully satisfied with it right now either

**Comment by kodiultimate** [comment]
Possible it could cause some issues on other devices unless is calculated correctly (safely for device) while auto-generated ?

**Comment by JayDigg** [comment]
Not a fan either. Writing advanced settings as soon as you start the build may be the worst time, since its using the most resources on first start to load everything up and Advanced settings is calculated  on current resources at the time. 
I took a suggestion from a friend and deleted the line: 
if not os.path.exists(ADVANCED): writeAdvanced()

in the startup.py

**Comment by drinfernoo** [comment]
@JayDigg That's probably the right way. There's no reason to add it unprovoked.

**Comment by JayDigg** [comment]
Agreed.

**Comment by kodiultimate** [comment]
> I took a suggestion from a friend and deleted the line:
> if not os.path.exists(ADVANCED): writeAdvanced()
> 
> in the startup.py

Thanks for the heads up.
Will do the same

**Comment by kodiultimate** [comment]
> since

**Comment by JayDigg** [comment]
> But I think it is generate on the first start up of the wizard before we actually download any build.

Yea, that makes sense.

**Comment by kodiultimate** [comment]
> > But I think it is generate on the first start up of the wizard before we actually download any build.
> 
> Yea, true that makes sense. Hmm, so thats probably the best time then... Unless it puts it to high at that time, then after the true resources are being used after the installation of a full build, it might cause a crash on lower power devices?

So I think the whole idea is wrong, but that's my opinion ;)
Lets the end user run advanced settings at their own convenient time and then wizard will set up it with the proper value for the device.
