### ISSUE TITLE
[Q] Real Debrid backups

### ISSUE THREAD

**Issue by JayDigg** [drinfernoo/plugin.program.aftermath#59]
More of a question. With the real debrid login backups. When the Wizard is set to back up Real Debrid, for example Seren addon. Is it backing up the entire Settings.xml? Or just the actual Real Debrid login? Because if it is the entire settings.xml, I think im going to disable that, because it takes a bit of setup like adding the scraper packages, setting it for Real Debrid, enabling Up Next, etc. So my fear is that if i set it all up in the build, and the user has old settings that has been backed up previously, if it saves the old unfunctional settings, it would restore the old settings and overwrite the updated settings I create with a build update. Am i making sense?  If it is in fact just the actual RD authorization, and not the full settings, this wouldnt be an issue. Just wanted to know exactly what is being backed up as far as Seren. Thanks!

**Comment by drinfernoo** [comment]
Only settings related to Debrid are saved/restored. This is the same for Trakt and Login/API Keys.

**Comment by JayDigg** [comment]
Ok, perfect, just wanted to make sure. Thank you!
