### ISSUE TITLE
[FEATURE]Could you create a create special paths feature. It was in the Ares wizard and I miss it. I build on a windows machine and run on Android boxes. It's great not to have to link images over again when I transfer the build.

### ISSUE THREAD

**Issue by victaming** [drinfernoo/plugin.program.aftermath#64]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kodiultimate** [comment]
I'm sure it is already there.

Convert to special....

**Comment by SerpentDrago** [comment]
this already exists in maintenance section  > Convert to special

**Comment by Jeffers24** [comment]
I understand the special path feature, I normally manually edit my paths to make them special.
If I choose Convert to special feature in the wizard how/what does it convert?
I have always been wary of using Covert to special, in case it changed paths that I didn't want to change, or didn't change all the paths I wanted changing.

**Comment by drinfernoo** [comment]
The `convertSpecial(...)` method, declared here:

https://github.com/drinfernoo/plugin.program.aftermath/blob/ad975550d58fcdb4d859f90a8d2f0e0bbbc26dff/resources/libs/wizard.py#L934-L956

Loops through all the files in `url`, which the wizard passes to the method as *xbmc.translatePath('special://home/')`, so all files in `special://home/`, essentially. Then, if that file is either a `.hash.`, `.properties', or `.xml` file, it *opens the file, and replaces any *physical* path references that correspond to `special://home/`, with... `special://home/`. While I agree that there may be other files besides those three types that may need to be converted to special paths, I think this covers a wide range of paths.

What other paths are you changing? What paths do you not want changed?

**Comment by drinfernoo** [comment]
Gonna go ahead and close this one until I see any reason to reopen it.
