### ISSUE TITLE
[QUESTION] Definition of 'old thumbnails'

### ISSUE THREAD

**Issue by kodiultimate** [drinfernoo/plugin.program.aftermath#66]
Hi,

Just quick question as I was always wondering.
What is the definition of 'old thumbnails' and when thumbnail classifying as old? Is there a certain time when they will classified as old and the they will get cleaned by wizard?

Thanks

**Comment by kodiultimate** [comment]
Ok, so I did had a look in wizard.py and finding line
def oldThumbs():
	dbfile = os.path.join(DATABASE, latestDB('Textures'))
	use    = 30
	week   = TODAY - timedelta(days=7)

Assuming thumbnails 7 days old will get deleted?

**Comment by drinfernoo** [comment]
That's essentially correct...

https://github.com/drinfernoo/plugin.program.aftermath/blob/ad975550d58fcdb4d859f90a8d2f0e0bbbc26dff/resources/libs/wizard.py#L2755

This is a SQL statement that basically says: "give me a list of all the textures that haven't been accessed more than `use` times, and that haven't been accessed in the last `week` days".

So "old" thumbnails are defined as "week old thumbnails" (as mentioned in the wizard's settings), *or* thumbnails that have been accessed less than 30 times. That means  if you have older thumbnails, but they're ones that get accessed often, they won't be deleted either.
